version: "3.8"

services:
  kafka:
    image: apache/kafka:latest
    container_name: stock
    environment:
      # -----------------------
      # KRaft mode setup
      # -----------------------
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"

      # -----------------------
      # Listener definitions
      # -----------------------
      # -----------------------
      # Listener definitions
      # -----------------------
      # Define two listeners: INTERNAL (for containers) and EXTERNAL (for host/localhost)
      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      # ðŸ’¥ This line tells Kafka which listener to use for controller comms
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # -----------------------
      # Broker behavior tuning
      # -----------------------
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - stock
    ports:
      - "9092:29092" # External access mapped to 29092 inside
      - "9093:9093"

    volumes:
      - kafka_stock:/var/lib/kafka/data

  redis:
    image: redis:8.2
    container_name: stock-redis
    ports:
      - "6379:6379"
    volumes:
      - stock_redis_data:/data
    networks:
      - stock
    command: redis-server --appendonly yes
  price_generator_service:
    build:
      context: ./price_generator
      dockerfile: Dockerfile
      target: dev
    container_name: price_generator
    env_file:
      - .env.docker
    volumes:
      - ./price_generator:/app
    networks:
      - stock
    depends_on:
      - kafka
  stock_processor_service:
    build:
      context: ./stock_processor
      dockerfile: Dockerfile
      target: dev
    container_name: stock_processor
    ports:
      - 3000:3000
    env_file:
      - .env.docker
    networks:
      - stock
    volumes:
      - ./stock_processor:/app

    depends_on:
      - kafka
      - redis
  stock_websocket_service:
    build:
      context: ./stock_websocket
      dockerfile: Dockerfile
      target: dev
    container_name: stock_websocket
    ports:
      - 8082:8082
    env_file:
      - .env.docker
    networks:
      - stock
    volumes:
      - ./stock_websocket:/app
    depends_on:
      - redis
volumes:
  kafka_stock:
  stock_redis_data:
networks:
  stock:
    driver: bridge
